"""add_press_reviews_table

Revision ID: 2a7893e4e9fd
Revises: 14da06184cdc
Create Date: 2026-05-13 17:49:19.681549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a7893e4e9fd'
down_revision: Union[str, Sequence[str], None] = '14da06184cdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('press_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('published_date', sa.String(length=20), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('pros', sa.JSON(), nullable=True),
    sa.Column('cons', sa.JSON(), nullable=True),
    sa.Column('verdict', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['vehicle_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_press_reviews_analysis_id'), 'press_reviews', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_press_reviews_source'), 'press_reviews', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_press_reviews_source'), table_name='press_reviews')
    op.drop_index(op.f('ix_press_reviews_analysis_id'), table_name='press_reviews')
    op.drop_table('press_reviews')
    # ### end Alembic commands ###
