"""add_pipeline_tables

Revision ID: 8a408ee49f03
Revises: 2a7893e4e9fd
Create Date: 2026-05-13 18:13:55.835880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a408ee49f03'
down_revision: Union[str, Sequence[str], None] = '2a7893e4e9fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('pipeline_type', sa.String(length=100), nullable=False),
    sa.Column('subject_type', sa.String(length=100), nullable=False),
    sa.Column('subject_data', sa.JSON(), nullable=False),
    sa.Column('subject_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('decision', sa.JSON(), nullable=True),
    sa.Column('skill_version', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_runs_pipeline_type'), 'pipeline_runs', ['pipeline_type'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_status'), 'pipeline_runs', ['status'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_subject_hash'), 'pipeline_runs', ['subject_hash'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_subject_type'), 'pipeline_runs', ['subject_type'], unique=False)
    op.create_table('pipeline_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('step_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('structured_result', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('depends_on', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_steps_run_id'), 'pipeline_steps', ['run_id'], unique=False)
    op.create_index(op.f('ix_pipeline_steps_status'), 'pipeline_steps', ['status'], unique=False)
    op.create_index(op.f('ix_pipeline_steps_step_type'), 'pipeline_steps', ['step_type'], unique=False)
    op.create_table('data_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('step_id', sa.UUID(), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['step_id'], ['pipeline_steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_sources_source_name'), 'data_sources', ['source_name'], unique=False)
    op.create_index(op.f('ix_data_sources_step_id'), 'data_sources', ['step_id'], unique=False)
    op.create_table('cache_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('data_source_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('structured_data', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cache_entries_data_source_id'), 'cache_entries', ['data_source_id'], unique=False)
    op.create_index(op.f('ix_cache_entries_is_current'), 'cache_entries', ['is_current'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cache_entries_is_current'), table_name='cache_entries')
    op.drop_index(op.f('ix_cache_entries_data_source_id'), table_name='cache_entries')
    op.drop_table('cache_entries')
    op.drop_index(op.f('ix_data_sources_step_id'), table_name='data_sources')
    op.drop_index(op.f('ix_data_sources_source_name'), table_name='data_sources')
    op.drop_table('data_sources')
    op.drop_index(op.f('ix_pipeline_steps_step_type'), table_name='pipeline_steps')
    op.drop_index(op.f('ix_pipeline_steps_status'), table_name='pipeline_steps')
    op.drop_index(op.f('ix_pipeline_steps_run_id'), table_name='pipeline_steps')
    op.drop_table('pipeline_steps')
    op.drop_index(op.f('ix_pipeline_runs_subject_type'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_subject_hash'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_status'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_pipeline_type'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    # ### end Alembic commands ###
